configuration/src/java/org/jimfarley/gadgets/GadgetAdminBean.java
/*
 * Copyright 2006 James A Farley
 */
package org.jimfarley.gadgets;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

@Stateless
@Name("gadgetAdmin")
public class GadgetAdminBean implements IGadgetAdminBean {
    @PersistenceContext(unitName="gadgetDatabase")
    private EntityManager mEntityManager;
    
    @In(value="gadget", create=true)
    private GadgetBean mActiveGadget;

	public GadgetBean getActiveGadget() {
		return mActiveGadget;
	}

	public void setActiveGadget(GadgetBean activeGadget) {
		mActiveGadget = activeGadget;
	}
    /** Retrieve all gadgets from the catalog, ordered by description */
    public List<GadgetBean> getAllGadgets() {
        List<GadgetBean> gadgets = new ArrayList<GadgetBean>();
        
        try {
            Query q = 
                mEntityManager.createQuery("select g from GadgetBean as g order by g.description");
            List gList = q.getResultList();
            Iterator i = gList.iterator();
            while (i.hasNext()) {
                gadgets.add((GadgetBean)i.next());
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        return gadgets;
    }

    /** Insert the gadget just created/edited into
     *  the catalog
     */
    public String newGadget() {
    	newGadget(getActiveGadget());
    	return "success";
    }
    
    /** Insert a new gadget into the catalog */
    public void newGadget(GadgetBean g) {
        try {
            mEntityManager.persist(g);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}

configuration/src/java/org/jimfarley/gadgets/GadgetBean.java
/*
 * Copyright 2006 James A Farley
 */
package org.jimfarley.gadgets;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.jboss.seam.annotations.Name;

@Entity
@Table(name="GADGET")
@Name("gadget")
public class GadgetBean implements Serializable {
	private long mId;
    private String mDescription = "";
    private String mType = "";
    
    public GadgetBean() { }
    
    @Id @GeneratedValue
    @Column(name="GADGET_ID")
    public long getId() {
    	return mId;
    }
    
    public void setId(long id) {
    	mId = id;
    }
    
    @Column(name="DESCR")
    public String getDescription() {
        return mDescription;
    }
    
    public void setDescription(String desc) {
        mDescription = desc;
    }

    @Column(name="TYPE")
    public String getType() {
        return mType;
    }

    public void setType(String t) {
        mType = t;
    }

    @Transient
    public Map<String,String> getGadgetTypes() {
        Map<String,String> types = new HashMap<String,String>();
        for (GadgetType value : GadgetType.values()) {
            types.put(value.label(), value.name());
        }
        return types;
    }
}

configuration/src/java/org/jimfarley/gadgets/IGadgetAdminBean.java
/*
 * Copyright 2006 James A Farley
 */
package org.jimfarley.gadgets;

import java.util.List;

import javax.ejb.Local;

@Local
public interface IGadgetAdminBean {
	public String newGadget();
    public void newGadget(GadgetBean g);
    public List<GadgetBean> getAllGadgets();
}

configuration/web/addGadget.jsp
<%@ page language="java" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://jboss.com/products/seam/taglib" prefix="s" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title>Add a Gadget</title>
</head>

<body>
    <f:view>
        <h:form>
            <table border="0">
                <tr>
                    <td>Description:</td>
                    <td>
                        <h:inputText value="#{gadget.description}"
                                     required="true" />
                    </td>
                </tr>
                <tr>
                    <td>Type:</td>
                    <td>
                        <h:selectOneMenu value="#{gadget.type}"
                                         required="true">
                            <f:selectItems value="#{gadget.gadgetTypes}" />
                        </h:selectOneMenu>
                    </td>
                </tr>
            </table>
            <h:commandButton type="submit" value="Create"
                             action="#{gadgetAdmin.newGadget}" />
        </h:form>
    </f:view>
</body>
</html>

configuration/web/listGadgets.jsp
<%@ page language="java" pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h"%>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f"%>
<%@ taglib uri="http://jboss.com/products/seam/taglib" prefix="s" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <title>Gadget List</title>
</head>

<body>
    <f:view>
        <h:messages/>
        <!--  Show the current gadget catalog -->
        <h:dataTable value="#{gadgetAdmin.allGadgets}" var="g">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Type" />
                </f:facet>
                <h:outputText value="#{g.type}" />
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Description" />
                </f:facet>
                <h:outputText value="#{g.description}" />
            </h:column>
        </h:dataTable>
        <h:form>
            <!-- Link to add a new gadget -->
            <s:link action="addGadget">
            	<h:outputText value="[Add a new gadget]"/>
           	</s:link>
        </h:form>
    </f:view>
</body>
</html>