bpm/src/java/org/jimfarley/gadgets/IGadgetAdminBean.java
/*
 * Copyright 2006 James A Farley
 */
package org.jimfarley.gadgets;

import javax.ejb.Local;

@Local
public interface IGadgetAdminBean {
    public String checkTypes();
    public String newGadget();
    public String editGadget();
    public String pickGadget();
    public String doneEdit();
	public String saveGadget();
    public String listGadgets();
    public void cancelGadget();
    public String cancelEditGadget();
    public void interimSaveGadget();
    public void saveGadget(Gadget g);
    public String getSearchField();
    public void setSearchField(String sf);
    public String search();
    public String saveGadgetType();
    public void saveGadgetType(GadgetType gt);
    public String saveGadgetFeature();
    public void saveGadgetFeature(GadgetFeature gf);
    public void deleteGadget(Gadget g);
    public void destroy();
}

bpm/web/index.jsp
<!DOCTYPE html PUBLIC 
    "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">
<ui:composition template="template.xhtml">
    <ui:param name="title" value="Home"/>
    <ui:define name="main">
      
    <f:view>
        <!--  Switch workspaces, if any exist -->
        <h:form rendered="#{!empty switcher.selectItems}">
            <h:commandButton action="#{switcher.select}" value="Jump to:"/>
            <h:selectOneMenu value="#{switcher.conversationIdOrOutcome}">
                <f:selectItems value="#{switcher.selectItems}"/>
            </h:selectOneMenu>
        </h:form>
        <!-- Link to add a new gadget -->
        <h:form>
            <table border="0">
                <tr>
                    <td class="formLabel">Find gadgets: </td>
                    <td class="formInput">
                        <h:inputText value="#{gadgetAdmin.searchField}"/>
                    </td>
                    <td>
                        <h:commandLink type="submit" value="Search"
                                       action="#{gadgetAdmin.search}">
                            <f:param name="conversationPropagation" value="begin"/>
                        </h:commandLink>
                    </td>
                </tr>
            </table>
            <s:link action="#{gadgetAdmin.newGadget}" value="Submit a new gadget"/>
        </h:form>
        <br/>
        <table>
            <tr>
                <td class="formLabel">Tasks assigned to you:</td>
            </tr>
            <tr>
                <td valign="top">
                    <h:dataTable rendered="#{identity.loggedIn and not empty taskInstanceList}"
                                 value="#{taskInstanceList}"
                                 var="task">
                        <h:column>
                            <f:facet name="header">Description</f:facet>
                            <h:outputText value="#{task.description}"/>
                        </h:column>
                        <h:column>
                            <s:link action="#{gadgetReview.startReviewTask}" 
                                    value="Begin" taskInstance="#{task}"/>
                        </h:column>
                    </h:dataTable>
                </td>
            </tr>
        </table>
    </f:view>
    </ui:define>
</ui:composition>
</html>

bpm/web/listGadgets.jsp
<!DOCTYPE html PUBLIC 
    "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">
<ui:composition template="template.xhtml">
    <ui:param name="title" value="Search Results"/>
    <ui:define name="main">
    <f:view>
        <!--  Show the matching gadgets, if any -->
        <h:outputText rendered="#{empty gadgetMatches}" 
                      value="No matching gadgets found."/>
        <h:dataTable rendered="#{!empty gadgetMatches}"
                     value="#{gadgetMatches}" var="selGadget"
                     columnClasses="dataCell">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Name" />
                </f:facet>
                <h:outputText value="#{selGadget.name}" />
            </h:column>
            
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Description" />
                </f:facet>
                <h:outputText value="#{selGadget.description}" />
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Type(s)"/>
                </f:facet>
                <h:outputText rendered="#{empty selGadget.types}"
                              value="No types assigned"/>
                <h:dataTable rendered="#{!empty selGadget.types}"
                             value="#{selGadget.types}" var="t">
                    <h:column>
                        <h:outputText value="#{t.label}" />
                    </h:column>
                </h:dataTable>
            </h:column>
            <h:column>
                <s:button value="Edit" 
                          action="#{gadgetAdmin.editGadget}" />
            </h:column>
        </h:dataTable>
        <h:form>
            <!-- Finish with these search results, end this conversation -->
            <s:link view="/admin/adminHome.seam" propagation="end">
            	<h:outputText value="Done"/>
           	</s:link>
        </h:form>
    </f:view>
    </ui:define>
</ui:composition>
</html>

bpm/web/login.jsp
<!DOCTYPE html PUBLIC 
    "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core">
<ui:composition template="template.xhtml">
    <ui:param name="title" value="Login"/>
    <ui:define name="main">
        <f:view>
            <h:form>
                <table border="0">
                    <tr>
                        <td class="formLabel">User name:</td>
                        <td>
                            <h:inputText value="#{identity.username}"
                                         id="name" 
                                         style="formInput"/>
                        </td>
                    </tr>
                    <tr>
                        <td class="formLabel">Password:</td>
                        <td>
                            <h:inputSecret value="#{identity.password}"
                                           id="password" 
                                           style="formInput"/>
                        </td>
                    </tr>
                </table>
                <h:commandButton value="Login"
                                 action="#{identity.login}"/>
            </h:form>
        </f:view>
    </ui:define>
</ui:composition>
</html>

bpm/web/template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
                      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:s="http://jboss.com/products/seam/taglib"
      xmlns:h="http://java.sun.com/jsf/html">

<head>
  <title>Gadget Catalog: #{title}</title>
  <link href="styles.css" rel="stylesheet" type="text/css"/>
</head>

<body>
    <table border="0" width="100%" class="headerTable">
        <tr>
            <td class="headerCell" colspan="2">
                Gadget Catalog: #{title}          
            </td>
        </tr>
        <tr>
            <td>
                <h:form>
                    <s:link view="/index.seam" propagation="none">
                        <h:outputText value="Home"/>
                    </s:link>
                </h:form>
            </td>
            <td align="right">
                <h:outputLink value="login.seam" 
                              rendered="#{not identity.loggedIn}">Log in</h:outputLink>
                <s:link action="#{identity.logout}" value="Log out" 
                        rendered="#{identity.loggedIn}"/>
            </td>
        </tr>
    </table>

    <div id="messages">
        <h:messages layout="table"
                    infoClass="infoMessage" 
                    errorClass="errorMessage"/>
    </div>
    <div id="main">
        <ui:insert name="main"/>
    </div>
</body>
</html>